### ISSUE TITLE
can you update to swift 3.0

### ISSUE THREAD

**Issue by reejosamuel** [96-problems/medium-sdk-swift#1]

**Comment by ferbass** [comment]
@reejosamuel it is on road map for next week, if you really need and can't wait, please send us a pull request ;)

**Comment by reejosamuel** [comment]
Ok

**Comment by reejosamuel** [comment]
also as a note, The pod file line in your readme says `MediumSDKManager` when its `MediumSDKswift`.

**Comment by reejosamuel** [comment]
#2 Created a PR
